# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  push:
    branches: 
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: terminal plugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: devbytom
          template: terminal
          base: header
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: "html, css, php"
          plugin_languages_skipped: ""
          plugin_lines: yes
      
      - name: tweets plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.svg
          user: devbytom
          plugin_tweets: yes
          committer_token: ${{ secrets.GITHUB_TOKEN }}
